server:
  port: 8001
spring:
  application:
    name: sonarqube-sample
  build:
    version: 0.0.1
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
logging:
  level:
    root: INFO
